version: "1"
context:
  active-host: "yj377.us1.dbt.com"
  active-project: "70471823429558"
projects:
  - project-name: "analyticsdbt"
    project-id: "70471823429558"
    account-name: "apple"
    account-id: "70471823424809"
    account-host: "yj377.us1.dbt.com"
    token-name: "cloud-cli-83ae"
    token-value: "dbtu_IIf_QvYlYXiaCwYaREkC7-nKum6kx7yl7FD5gQn6tm54EuAkCQ"
